services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/src:/app/src
      - ./fastapi/resource:/app/resource
      - ./fastapi/src/sql_app.db:/app/sql_app.db
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./sql_app.db
    restart: always

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit/src:/app/src
      - ./streamlit/resource:/app/resource
    environment:
      - FASTAPI_URL=http://fastapi:8000
    restart: always