version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile_prod
    ports:
      - "8000:8000"
    # volumes:
    #   - ./fastapi:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./sql_app.db

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile_prod
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    # volumes:
    #   - ./streamlit:/app
    environment:
      - FASTAPI_URL=http://fastapi:8000
