credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: admin
      password: abc # Will be hashed automatically
    user:
      email: user@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: user
      password: def # Will be hashed automatically
  roles:
    admin: ["admin"]  # 管理者ユーザーのロールリスト
    user: ["user"]    # 一般ユーザーのロールリスト
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com